# Generated by Django 2.0.3 on 2018-03-26 03:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('description', models.TextField()),
                ('added', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-added',),
            },
        ),
    ]
