# Generated by Django 2.0.3 on 2018-03-27 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baser',
            name='science',
            field=models.CharField(default='math', max_length=100),
            preserve_default=False,
        ),
    ]
